version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
    volumes:
      - .:/app
    restart: unless-stopped